Repository intel-staging/libptpmgmt_iaclocklib, pull requests merged in 2025-06, with the labels that each got.

#229 clkmgr: Remove unused variable.
  clkmgr/client/timebase_state.cpp
  clkmgr/client/timebase_state.hpp
Labels: code_improvement

#231 clkmgr: Refactor subscription handling.
  clkmgr/client/timebase_configs.cpp
  clkmgr/common/timebase.hpp
  clkmgr/proxy/config_parser.cpp
  clkmgr/pub/clkmgr/timebase_configs.h
  clkmgr/sample/clkmgr_test.cpp
  clkmgr/utest/timebase_configs.cpp
Labels: code_enhancement, feature_enhancement

#230 clkmgr: Improve event mask validation in subscription logic
  clkmgr/client/subscription.cpp
  clkmgr/client/timebase_state.cpp
  clkmgr/client/timebase_state.hpp
  clkmgr/common/types.m4
  clkmgr/pub/clkmgr/subscription.h
  clkmgr/utest/subscription.cpp
Labels: code_enhancement, issue_resolution

#235 clkmgr: Add unit test for pub API.
  clkmgr/utest/Makefile
  clkmgr/utest/clockmanager.cpp
Labels: create_tests

#244 clkmgr: Refactor clock type parameters to use Clkmgr_ClockType enum
  clkmgr/client/clock_event.cpp
  clkmgr/client/subscription.cpp
  clkmgr/common/types.m4
  clkmgr/pub/clkmgr/event_c.h
  clkmgr/pub/clkmgr/subscription_c.h
Labels: code_enhancement, code_improvement

#245 clkmgr: Refactor syncInterval type to uint64_t
  clkmgr/client/clock_event.cpp
  clkmgr/common/types.m4
  clkmgr/pub/clkmgr/event.h
  clkmgr/pub/clkmgr/event_c.h
  clkmgr/pub/clkmgr/timebase_configs.h
  clkmgr/pub/clkmgr/timebase_configs_c.h
Labels: code_enhancement
